image: registry.0xacab.org/team-friendo/signalboost/signalboost

variables:
  NODE_ENV: test
  POSTGRES_DB: signalboost_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust

cache:
  paths:
    - node_modules/

test_lint:
  script:
    - yarn install
    - npx eslint app && npx eslint test
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test_unit:
  services:
    - name: postgres:12
      alias: db
  script:
    - yarn install
    - npx sequelize db:migrate --env test
    - cd test/unit
    - find . -name '*.spec.js' | shuf | xargs npx mocha -R spec -r babel-register --reporter dot --exit
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

test_integration:
  variables:
    INTEGRATION_TEST: 1
  services:
    - name: postgres:12
      alias: db
  script:
    - yarn install
    - npx sequelize db:migrate --env test
    - cd test/integration
    - find . -name '*.spec.js' | shuf | xargs npx mocha -R spec -r babel-register --reporter dot --exit
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'