variables:
  NODE_ENV: test
  POSTGRES_DB: signalboost_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  SB_IMAGE: registry.0xacab.org/team-friendo/signalboost/signalboost:latest
  SC_IMAGE: registry.0xacab.org/team-friendo/signalboost/signalc:latest

cache:
  paths:
    - node_modules/
    - /home/gradle/.gradle

stages:
  - build
  - test

################
# shared logic #
################

.mr-only:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'

###############
# BUILD STAGE #
###############

build:sb:
  stage: build
  image: $SB_IMAGE
  extends: .mr-only
  services:
    - name: postgres:12
      alias: db
  script:
    - yarn install
    - npx sequelize db:migrate --env test

build:sc:
  stage: build
  image: $SC_IMAGE
  extends: .mr-only
  script:
    - cd signalc
    - gradle build

##############
# TEST STAGE #
##############

test:sb_lint:
  image: $SB_IMAGE
  stage: test
  extends: .mr-only
  script:
    - npx eslint app && npx eslint test

test:sb_unit:
  stage: test
  image: $SB_IMAGE
  extends: .mr-only
  services:
    - name: postgres:12
      alias: db
  script:
    - NODE_ENV=test npx mocha ./test/unit  -name '*.spec.js' --recursive -r babel-register --reporter dot --exit

test:sb_integration:
  stage: test
  image: $SB_IMAGE
  extends: .mr-only
  variables:
    INTEGRATION_TEST: 1
  services:
    - name: postgres:12
      alias: db
  script:
    - NODE_ENV=test npx mocha ./test/integration  -name '*.spec.js' --recursive -r babel-register --reporter dot --exit

test:sc:
  stage: test
  image: $SC_IMAGE
  extends: .mr-only
  script:
    - cd signalc
    - gradle test
