version: '3.4'

x-signald-base: &signald-base
  image: registry.0xacab.org/team-friendo/signalboost/signald
  environment:
    SIGNALBOOST_HOST_IP: ${SIGNALBOOST_HOST_IP}
    SIGNALD_VERBOSE_LOG: ${SIGNALD_VERBOSE_LOG:-0}
  networks:
    - default
  restart: always


volumes:

  postgres_data:
  signal_data:
  signald_sock_0:
  signald_sock_1:
  signald_sock_2:
  signald_sock_3:
  signald_sock_4:
  signald_sock_5:
  signald_sock_6:
  signald_sock_7:


services:

  db:
    image: postgres:12
    container_name: signalboost_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    restart: always

  app:
    image: registry.0xacab.org/team-friendo/signalboost/signalboost:latest
    container_name: signalboost_app
    depends_on:
      - db
      - signald_0
      - signald_1
      - signald_2
      - signald_3
      - signald_4
      - signald_5
      - signald_6
      - signald_7
    entrypoint: /signalboost/bin/entrypoint/app
    environment:
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-EN}
      DB_HOST: db
      NODE_ENV: ${NODE_ENV:-development}
      PROJECT_ROOT: ${PWD}
      SIGNALBOOST_VERBOSE_LOG: ${SIGNALBOOST_VERBOSE_LOG:-0}
      REREGISTER_ON_STARTUP: ${REREGISTER_ON_STARTUP:-0}
    expose:
      - 3000
    networks:
      - default
    volumes:
      - ./.sequelizerc:/signalboost/.sequelizerc
      - ./app:/signalboost/app
      - ./bin:/signalboost/bin
      - ./node_modules:/signalboost/node_modules
      - ./package.json:/signalboost/package.json
      - ./yarn.lock:/signalboost/yarn.lock
      - /var/run/docker.sock:/var/run/docker.sock
      - signal_data:/var/lib/signald/data
      - signald_sock_0:/var/run/signald-sockets/0
      - signald_sock_1:/var/run/signald-sockets/1
      - signald_sock_2:/var/run/signald-sockets/2
      - signald_sock_3:/var/run/signald-sockets/3
      - signald_sock_4:/var/run/signald-sockets/4
      - signald_sock_5:/var/run/signald-sockets/5
      - signald_sock_6:/var/run/signald-sockets/6
      - signald_sock_7:/var/run/signald-sockets/7

    restart: always

  signald_0:
    <<: *signald-base
    container_name: signalboost_signald_0
    environment:
      METRICS_PORT: 5000
    expose:
      - 5000
    volumes:
      - signald_sock_0:/var/run/signald/
      # NOTE: we would like to DRY this up by extracting the below 4 volumes to &signald-base,
      # but can't b/c yml doesn't support list merging and leveraging docker-compose's ability
      # to merge lists between base and override files seems indirect and confusing (and unDRY)
      # when we would have to place socket file overrides that are the same in dev and prod
      # in the respective override files for dev and prod.for context see:
      # https://stackoverflow.com/questions/61178058/docker-compose-merge-arrays-for-yaml-aliases-and-anchors
      - signal_data:/var/lib/signald/data
      - ./bin:/signalboost/bin
      - ./signald/jmx:/var/lib/jmx
      - ./backups:/backups

  signald_1:
    <<: *signald-base
    container_name: signalboost_signald_1
    environment:
      METRICS_PORT: 5001
    expose:
      - 5001
    volumes:
      - signald_sock_1:/var/run/signald/
      - signal_data:/var/lib/signald/data
      - ./bin:/signalboost/bin
      - ./signald/jmx:/var/lib/jmx
      - ./backups:/backups

  signald_2:
    <<: *signald-base
    container_name: signalboost_signald_2
    environment:
      METRICS_PORT: 5002
    expose:
      - 5002
    volumes:
      - signald_sock_2:/var/run/signald/
      - signal_data:/var/lib/signald/data
      - ./bin:/signalboost/bin
      - ./signald/jmx:/var/lib/jmx
      - ./backups:/backups

  signald_3:
    <<: *signald-base
    container_name: signalboost_signald_3
    environment:
      METRICS_PORT: 5003
    expose:
      - 5003
    volumes:
      - signald_sock_3:/var/run/signald/
      - signal_data:/var/lib/signald/data
      - ./bin:/signalboost/bin
      - ./signald/jmx:/var/lib/jmx
      - ./backups:/backups

  signald_4:
    <<: *signald-base
    container_name: signalboost_signald_4
    environment:
      METRICS_PORT: 5004
    expose:
      - 5004
    volumes:
      - signald_sock_4:/var/run/signald/
      - signal_data:/var/lib/signald/data
      - ./bin:/signalboost/bin
      - ./signald/jmx:/var/lib/jmx
      - ./backups:/backups

  signald_5:
    <<: *signald-base
    container_name: signalboost_signald_5
    environment:
      METRICS_PORT: 5005
    expose:
      - 5005
    volumes:
      - signald_sock_5:/var/run/signald/
      - signal_data:/var/lib/signald/data
      - ./bin:/signalboost/bin
      - ./signald/jmx:/var/lib/jmx
      - ./backups:/backups

  signald_6:
    <<: *signald-base
    container_name: signalboost_signald_6
    environment:
      METRICS_PORT: 5006
    expose:
      - 5006
    volumes:
      - signald_sock_6:/var/run/signald/
      - signal_data:/var/lib/signald/data
      - ./bin:/signalboost/bin
      - ./signald/jmx:/var/lib/jmx
      - ./backups:/backups

  signald_7:
    <<: *signald-base
    container_name: signalboost_signald_7
    environment:
      METRICS_PORT: 5007
    expose:
      - 5007
    volumes:
      - signald_sock_7:/var/run/signald/
      - signal_data:/var/lib/signald/data
      - ./bin:/signalboost/bin
      - ./signald/jmx:/var/lib/jmx
      - ./backups:/backups
