version: '3.4'

# NOTE:
#
# we create a `localdev` network w/ a non-standard subnet mask to be able to use
# use docker from behdind a VPN, which is often necessary to auth w/ Signal.
# (see: https://github.com/docker/for-linux/issues/418#issuecomment-491323611)
#
# USAGE:
#
# for this to work you must first run the following (which is done automatically
# by `make _.setup`):
#
# ```bash
# docker network create localdev --subnet 10.0.1.0/24
# ```

networks:
  default:
    external:
      name: localdev

volumes:
  # postgres_data:
  signal_sock:
  signal_data:
  simulator_sock:

services:
  db:
    image: postgres:12
    container_name: load_test_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - 0.0.0.0:5432:5432
    restart: unless-stopped

  signald_app:
    image: team-friendo/signalboost/signald:load
    container_name: load_test_signald_app
    env_file: .env.dev
    environment:
      SIGNALD_VERBOSE_LOG: ${SIGNALD_VERBOSE_LOG:-0}
    networks:
      - default
    expose:
      - 1312
    ports:
      - 0.0.0.0:9010:9010
      - 0.0.0.0:8017:8016
    volumes:
      - ./bin:/signalboost/bin
      - ./signald/jmx:/var/lib/jmx
      - signal_data:/var/lib/signald/data
      - signal_sock:/var/run/signald/
    restart: unless-stopped

  signald_simulator:
    image: team-friendo/signalboost/signald:load
    container_name: load_test_signald_simulator
    env_file: .env.dev
    environment:
      SIGNALD_VERBOSE_LOG: 0
    networks:
      - default
    expose:
      - 1313
    ports:
      - 0.0.0.0:9011:9011
      - 0.0.0.0:8016:8016
    volumes:
      - ./bin:/signalboost/bin
      - signal_data:/var/lib/signald/data
      - simulator_sock:/var/run/signald/
    restart: unless-stopped

  sigarillo:
    image: registry.0xacab.org/team-friendo/signalboost/sigarillo:latest
    container_name: load_test_sigarillo
    ports:
      - 0.0.0.0:3000:3000
    volumes:
      - ./sigarillo/libsignal-overrides/production.json:/opt/sigarillo/node_modules/@throneless/libsignal-service/config/production.json
      - ./sigarillo/libsignal-overrides/WebAPI.js:/opt/sigarillo/node_modules/@throneless/libsignal-service/src/WebAPI.js
    environment:
      - SECRETS=change_me
      - NODE_ENV=production
      - DB_CLIENT=pg
      - DB_CONNECTION=postgres://sigarillo:sigarillo@db:5432/sigarillo

  app:
    image: registry.0xacab.org/team-friendo/signalboost/signalboost
    container_name: load_test_app
    depends_on:
      - db
    entrypoint: /signalboost/bin/entrypoint/app
    env_file: .env.dev
    environment:
      SIGNALBOOST_VERBOSE_LOG: ${SIGNALBOOST_VERBOSE_LOG:-0}
      PROJECT_ROOT: ${PWD}
      NODE_ENV: ${NODE_ENV:-development}
      DEFAULT_LANGUAGE: ${DEFAULT_LANGUAGE:-EN}
      REREGISTER_ON_STARTUP: ${REREGISTER_ON_STARTUP:-0}
    expose:
      - 3000
    networks:
      - default
    volumes:
      - ./.sequelizerc:/signalboost/.sequelizerc
      - ./app:/signalboost/app
      - ./bin:/signalboost/bin
      - ./node_modules:/signalboost/node_modules
      - ./package.json:/signalboost/package.json
      - signal_data:/var/lib/signald/data
      - signal_sock:/var/run/signald/
      - ./yarn.lock:/signalboost/yarn.lock
    restart: unless-stopped

  simulator:
    image: registry.0xacab.org/team-friendo/signalboost/signalboost
    container_name: load_test_simulator
    depends_on:
      - db
    entrypoint: /signalboost/bin/entrypoint/simulator
    env_file: .env.dev
    expose:
      - 3001
    networks:
      - default
    volumes:
      - ./.sequelizerc:/signalboost/.sequelizerc
      - ./app:/signalboost/app
      - ./simulator:/signalboost/simulator
      - ./bin:/signalboost/bin
      - ./node_modules:/signalboost/node_modules
      - ./package.json:/signalboost/package.json
      - signal_data:/var/lib/signald/data
      - simulator_sock:/var/run/signald/
      - ./yarn.lock:/signalboost/yarn.lock
    restart: unless-stopped

  signal_server:
    image: registry.0xacab.org/team-friendo/signalboost/signal-server:3.21
    container_name: load_test_signal_server
    depends_on:
      - db
      - redis
    ports:
      - 0.0.0.0:8015:8015
      - 0.0.0.0:8080:8080
      - 0.0.0.0:8081:8081

  redis:
    image: redis
    container_name: load_test_signal_redis
    ports:
      - 0.0.0.0:6379:6379
    restart: always

  # prefer ngrok_signalboost, need to change url to ngrok in app entrypoint
  signalboost_ngrok:
    container_name: load_test_app_signalboost_ngrok
    ports:
      - 0.0.0.0:4040:4040
    networks:
      - default
    image: wernight/ngrok
    links:
      - app
    env_file: .env.dev
    environment:
      - NGROK_PORT=app:3000
    restart: unless-stopped

  ngrok_simulator:
    container_name: load_test_ngrok_simulator
    ports:
      - 0.0.0.0:4041:4040
    networks:
      - default
    image: wernight/ngrok
    links:
      - signal_server
    env_file: .env.dev
    environment:
      - NGROK_PORT=signal_server:8080
    restart: unless-stopped

  localtunnel:
    image: efrecon/localtunnel
    links:
      - signal_server
    command:
      --local-host signal_server --port 8080 --subdomain sb-load