version: '3'

# NOTE: the below directive makes it possible to run tests behind a VPN
# (feel free to comment it out if it breaks anythuing for you!)

networks:
  default:
    external:
      name: localdev

volumes:
  postgres_data:
  logs:

services:
  db:
    image: postgres:12
    container_name: test_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
  signalboost:
    image: registry.0xacab.org/team-friendo/signalboost/signalboost:latest
    container_name: test_signalboost
    env_file: .env.test
    depends_on:
      - db
    volumes:
      - ./.sequelizerc:/signalboost/.sequelizerc
      - ./app:/signalboost/app
      - ./bin:/signalboost/bin
      - ./node_modules:/signalboost/node_modules
      - ./package.json:/signalboost/package.json
      - ./test:/signalboost/test
      - ./yarn.lock:/signalboost/yarn.lock
  signalc:
    image: registry.0xacab.org/team-friendo/signalboost/signalc:latest
    container_name: test_signalc
    env_file: .env.test
    depends_on:
      - db
    volumes:
      - ./signalc:/signalc
      - ./bin:/signalc/bin
