version: '3.4'

# this file contains configs for prod isntance of signalboost
# see docker-compose.yml for defaults extended here

x-loki-logging: &loki-logging
  options:
    loki-url: ${LOKI_URL}
  driver: loki

x-signald-overrides: &signald-overrides
  logging: *loki-logging
  networks:
    - default
    - proxy-tier

networks:
  proxy-tier:

volumes:
  certs:
  html:
  acme_config:

services:

  app:
    env_file: .env
    environment:
      NODE_ENV: production
      LETSENCRYPT_HOST: ${SIGNALBOOST_HOST_URL}
      VIRTUAL_HOST: ${SIGNALBOOST_HOST_URL}
      VIRTUAL_PORT: 3000
    logging: *loki-logging
    networks:
      - proxy-tier

  signald_0:
    <<: *signald-overrides
    environment:
      LETSENCRYPT_HOST: ${SIGNALD_HOST_URL_0}
      VIRTUAL_HOST: ${SIGNALD_HOST_URL_0}
      VIRTUAL_PORT: 5000

  signald_1:
    <<: *signald-overrides
    environment:
      LETSENCRYPT_HOST: ${SIGNALD_HOST_URL_1}
      VIRTUAL_HOST: ${SIGNALD_HOST_URL_1}
      VIRTUAL_PORT: 5001

  signald_2:
    <<: *signald-overrides
    environment:
      LETSENCRYPT_HOST: ${SIGNALD_HOST_URL_2}
      VIRTUAL_HOST: ${SIGNALD_HOST_URL_2}
      VIRTUAL_PORT: 5002

  signald_3:
    <<: *signald-overrides
    environment:
      LETSENCRYPT_HOST: ${SIGNALD_HOST_URL_3}
      VIRTUAL_HOST: ${SIGNALD_HOST_URL_3}
      VIRTUAL_PORT: 5003

  signald_4:
    <<: *signald-overrides
    environment:
      LETSENCRYPT_HOST: ${SIGNALD_HOST_URL_4}
      VIRTUAL_HOST: ${SIGNALD_HOST_URL_4}
      VIRTUAL_PORT: 5004

  signald_5:
    <<: *signald-overrides
    environment:
      LETSENCRYPT_HOST: ${SIGNALD_HOST_URL_5}
      VIRTUAL_HOST: ${SIGNALD_HOST_URL_5}
      VIRTUAL_PORT: 5002

  signald_6:
    <<: *signald-overrides
    environment:
      LETSENCRYPT_HOST: ${SIGNALD_HOST_URL_6}
      VIRTUAL_HOST: ${SIGNALD_HOST_URL_6}
      VIRTUAL_PORT: 5003

  signald_7:
    <<: *signald-overrides
    environment:
      LETSENCRYPT_HOST: ${SIGNALD_HOST_URL_7}
      VIRTUAL_HOST: ${SIGNALD_HOST_URL_7}
      VIRTUAL_PORT: 5004

  proxy:
    image: jwilder/nginx-proxy:0.8.0
    container_name: signalboost_proxy
    ports:
      - 80:80
      - 443:443
    labels:
      com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy: "true"
    volumes:
      - certs:/etc/nginx/certs:ro
      - ./nginx/vhost.d:/etc/nginx/vhost.d:ro
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    logging: *loki-logging
    restart: always

  letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:2.0.2
    container_name: signalboost_letsencrypt
    restart: always
    volumes:
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - ./nginx/vhost.d:/etc/nginx/vhost.d
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme_config:/etc/acme.sh
    networks:
      - proxy-tier
    logging: *loki-logging
    depends_on:
      - proxy
