db:
  url: "jdbc:pgsql://localhost:5432/signalc"
  user: "postgres"
  driver: "com.impossibl.postgres.jdbc.PGDriver"
signal:
  agent: "signalc"
  addSecurityProvider: true
  trustStorePath: "/signalc/whisper.store"
  trustStorePassword: "whisper"
  zkGroupServerPublicParams:  "AMhf5ywVwITZMsff/eCyudZx9JDmkkkbV6PInzG4p8x3VqVJSFiMvnvlEKWuRob/1eaIetR31IYeAbm0NdOuHH8Qi+Rexi1wLlpzIo1gstHWBfZzy1+qHRV5A4TqPp15YzBPm0WSggW6PbSn+F4lf57VCnHF7p8SvzAA2ZZJPYJURt8X7bbg+H3i+PEjH9DXItNEqs2sNcug37xZQDLm7X0="
  serviceUrl:  "https://textsecure-service.whispersystems.org"
  cdnUrl:  "https://cdn.signal.org"
  cdn2Url:  "https://cdn2.signal.org"
  contactDiscoveryUrl:  "https://cms.souqcdn.com"
  keyBackupServiceUrl:  "https://api.backup.signal.org"
  storageUrl:  "https://storage.signal.org"
store:
  account: 'SQL'
  signalProtocol: 'SQL'