---
- name: Deploy Signalboost
  become: true
  hosts: "{{ sb_host | default('signalboost') }}"

  environment:
    NODE_ENV: production

  vars:
    homedir: /srv/signalboost
    host_url: "{{ lookup('env', 'SIGNALBOOST_HOST_URL') }}"
    api_token: "{{ lookup('env', 'SIGNALBOOST_API_TOKEN') }}"
    env_file: "files/.env"
    secrets_method: copy

  tasks:

  #########
  # CLONE #
  #########

  - name: Pull signalboost repository from 0xacab
    git:
      repo: https://0xacab.org/team-friendo/signalboost
      dest: "{{ homedir }}"
      force: true
      version: "{{ branch | default('main') }}"
    tags: clone

  - name: Deploy environment file using blackbox
    command: ./bin/blackbox/postdeploy
    args:
      chdir: "{{ homedir }}"
    tags: clone
    when: secrets_method == "blackbox"

  - name: Deploy environment file by copying local file
    copy:
      src: "{{ env_file }}"
      dest: "{{ homedir }}/.env"
    tags: clone
    when: secrets_method == "copy"

  - name: Deploy vhost.d files by copying local file
    copy:
      src: "files/vhost.d"
      dest: "{{ homedir }}/nginx/"
    tags: clone
    when: secrets_method == "copy"


  ########
  # STOP #
  ########

  - name: Stop app
    command: ./bin/shutdown
    args:
      chdir: "{{ homedir }}"
    tags: stop

  ###########
  # PREPARE #
  ###########

  - name: Pull latest signalboost container
    command: "docker-compose pull app"
    args:
      chdir: "{{ homedir }}"
    tags: prepare, docker

  - name: Pull latest signald container
    command: "docker-compose pull signald_0"
    args:
      chdir: "{{ homedir }}"
    tags: prepare, docker

    # to ensure ACMEv2 compatibility
    # (as per, e.g.: https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion/issues/598)
  - name: Pull latest version of letsencrypt companion
    command: "docker-compose pull letsencrypt"
    args:
      chdir: "{{ homedir }}"
    tags: prepare, docker

  - name: Install node packages
    command: "docker-compose run --entrypoint '/signalboost/bin/entrypoint/install' app"
    args:
      chdir: "{{ homedir }}"
    tags: prepare

  - name: Setup database, run migrations
    command: "docker-compose run --entrypoint /signalboost/bin/db/setup-sb app"
    args:
      chdir: "{{ homedir }}"
    tags: prepare

  - name: Stop containers used for install & db setup
    command: "docker-compose down"
    args:
      chdir: "{{ homedir }}"
    tags: prepare

  #########
  # START #
  #########

  - name: Start app
    command: "docker-compose --env-file .env up -d"
    args:
      chdir: "{{ homedir }}"
    register: docker_up_result

  # - debug:
  #     var: docker_up_result

  ######################
  # AVAILABILITY CHECK #
  ######################

  - name: Ping instance until it is available
    shell: SIGNALBOOST_API_TOKEN="{{ api_token }}" SIGNALBOOST_HOST_URL="{{ host_url }}" ./bin/check-availability
    args:
      chdir: "{{ homedir }}"
    register: health_check_output
    changed_when: false
    failed_when: health_check_output.rc != 0
    tags: health_check
