{
 "title": "Signalboost node app",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "channel_messages_in_flight: avg / sec over last 1h",
   "type": "graph",
   "description": "The number of messages per channel that signalboost has sent but not yet received receipt of from signald. Average in flight messages per second over the last hour.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(channel_messages_in_flight[1h])"
    }
   ]
  },
  {
   "title": "Heap available / used",
   "type": "graph",
   "description": "Purple is process heap in bytes. Lower yellow line is nodejs heap used.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_heap_size_used_bytes" },
    {
     "expr": "nodejs_heap_space_size_available_bytes"
    },
    { "expr": "process_heap_bytes" }
   ]
  },
  {
   "title": "signald_message_count (avg / sec over last 1h)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(signald_message_count[1h])  "
    }
   ]
  },
  {
   "title": "File descriptors: max / open",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "process_open_fds" },
    { "expr": "process_max_fds" }
   ]
  },
  {
   "title": "channel_message_count (avg / sec over last 1h)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(channel_message_count[1h])"
    }
   ]
  },
  {
   "title": "Process active requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "nodejs_active_requests_total" }
   ]
  },
  {
   "title": "Uptime",
   "type": "graph",
   "description": "Time at 1.00 is time app is up.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "up" }
   ]
  },
  {
   "title": "Node GC seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_gc_duration_seconds_count"
    }
   ]
  },
  {
   "title": "Node GC Duration (sec) bucket",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(nodejs_gc_duration_seconds_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}